/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppArticles: typeof import('./src/components/AppArticles.vue')['default']
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppCompanies: typeof import('./src/components/AppCompanies.vue')['default']
    AppForm: typeof import('./src/components/AppForm.vue')['default']
    AppMode: typeof import('./src/components/AppMode.vue')['default']
    AppSidenav: typeof import('./src/components/AppSidenav.vue')['default']
    AppUser: typeof import('./src/components/AppUser.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Galleria: typeof import('primevue/galleria')['default']
    HeaderView: typeof import('./src/components/HeaderView.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
