name: Frontend Deploy

on:
  push:
    branches: [main] # or change to 'master' or any branch you're using

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          ssh-keyscan -H 13.211.219.32 >> ~/.ssh/known_hosts

      - name: Debug SSH
        run: ssh -vvv -i ~/.ssh/authorized_keys ubuntu@13.211.219.32 echo "Connection Successful"

      - name: Deploy to EC2
        run: |
          ssh ubuntu@13.211.219.32 '
            cd ~/app/web-dashoard/vue-web-dashboard &&
            git pull &&
            npm install &&
            npm run build
          '